--
-- PostgreSQL database dump
--

\restrict YO0qSIbIRlvW0aI8jiFZ0dvDPRCP0OeMgbHLefTIPTK7yWXOabHUbGdbmdHhfym

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_status (
    id bigint NOT NULL,
    cpr_id uuid,
    start_at timestamp without time zone,
    environment character varying(100),
    services jsonb,
    description text,
    activities character varying(255),
    end_at timestamp without time zone,
    last_operation timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.audit_status OWNER TO postgres;

--
-- Name: audit_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_status ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.audit_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: channel_reception; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.channel_reception (
    id bigint NOT NULL,
    name character varying(100),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.channel_reception OWNER TO postgres;

--
-- Name: channel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.channel_reception ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collectives; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collectives (
    id integer NOT NULL,
    group_id integer,
    user_id character varying(15),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.collectives OWNER TO postgres;

--
-- Name: collectives_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.collectives ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collectives_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: components; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.components (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    product_id integer,
    description text,
    is_active boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.components OWNER TO postgres;

--
-- Name: components_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact (
    id bigint NOT NULL,
    customer_id character varying(20),
    name character varying(225),
    surname character varying(225),
    email character varying(225),
    phone character varying(11),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.contact OWNER TO postgres;

--
-- Name: contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_product_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer_product_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    customer_id integer,
    product_id integer,
    role_id integer,
    parent_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.customer_product_roles OWNER TO postgres;

--
-- Name: customer_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer_role (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.customer_role OWNER TO postgres;

--
-- Name: customer_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id integer NOT NULL,
    rif character varying(20) NOT NULL,
    name character varying(225),
    channel character varying(100),
    ws_group character varying(100),
    uid_sypago character varying(200),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departament; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departament (
    id integer NOT NULL,
    name character varying(100),
    is_active boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.departament OWNER TO postgres;

--
-- Name: departament_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departament ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departament_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: environment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.environment (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.environment OWNER TO postgres;

--
-- Name: environment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.environment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.environment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item_activities (
    id bigint NOT NULL,
    product_id integer,
    name character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.item_activities OWNER TO postgres;

--
-- Name: item_activities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item_activities ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.item_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notes (
    id integer NOT NULL,
    ticket_id character varying(13),
    task_id character varying(13),
    topic text NOT NULL,
    description text,
    created_by character varying(15),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_validation_null_task_ticket CHECK ((((ticket_id IS NOT NULL) AND (task_id IS NULL)) OR ((ticket_id IS NULL) AND (task_id IS NOT NULL))))
);


ALTER TABLE public.notes OWNER TO postgres;

--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    recipient_id character varying(15),
    sender_id character varying(15),
    ticket_id character varying(13),
    task_id character varying(13),
    type character varying(225),
    title text NOT NULL,
    message text,
    read_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_validation_null_task_ticket CHECK ((((ticket_id IS NOT NULL) AND (task_id IS NULL)) OR ((ticket_id IS NULL) AND (task_id IS NOT NULL))))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    module character varying(100),
    description text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: priority; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.priority (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.priority OWNER TO postgres;

--
-- Name: priority_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.priority ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.priority_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    is_active boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subproduct (
    id bigint NOT NULL,
    name character varying(100),
    product_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.subproduct OWNER TO postgres;

--
-- Name: product_services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subproduct ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.product_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: request_task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_task (
    id character varying(13) NOT NULL,
    ticket_id character varying(13),
    priority character varying(100) NOT NULL,
    status character varying(100) NOT NULL,
    cretaed_by character varying(15),
    assigned_departament integer,
    assigned_user character varying(15),
    topic text NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expired_in timestamp without time zone,
    closed_in timestamp without time zone
);


ALTER TABLE public.request_task OWNER TO postgres;

--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    role_id integer NOT NULL,
    permissions_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sla; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sla (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    unit_time_id character varying(100) NOT NULL,
    amount integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.sla OWNER TO postgres;

--
-- Name: sla_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sla ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sla_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.status (
    id integer NOT NULL,
    name character varying(100),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.status OWNER TO postgres;

--
-- Name: status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subcomponents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subcomponents (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    components_id integer,
    description text,
    is_active boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.subcomponents OWNER TO postgres;

--
-- Name: subcomponents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subcomponents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subcomponents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_break; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_break (
    id integer NOT NULL,
    task_id character varying(13),
    status_paused character varying(50) NOT NULL,
    start_at timestamp without time zone,
    end_at timestamp without time zone
);


ALTER TABLE public.task_break OWNER TO postgres;

--
-- Name: task_break_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_break ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_break_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_break; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_break (
    id integer NOT NULL,
    ticket_id character varying(13),
    status_paused character varying(50) NOT NULL,
    start_at timestamp without time zone,
    end_at timestamp without time zone
);


ALTER TABLE public.ticket_break OWNER TO postgres;

--
-- Name: ticket_break_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket_break ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_break_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_request (
    id character varying(13) NOT NULL,
    reported_by_customer_id character varying(20) NOT NULL,
    affected_customer_id character varying(20) NOT NULL,
    ticket_bcv character varying(12) NOT NULL,
    enviroment character varying(100) NOT NULL,
    priority character varying(100) NOT NULL,
    type_request character varying(100) NOT NULL,
    sla_id integer,
    components_id integer,
    subcomponents_id integer,
    contact_id integer,
    topic text,
    description text,
    cretaed_by character varying(15),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expired_in timestamp without time zone
);


ALTER TABLE public.ticket_request OWNER TO postgres;

--
-- Name: ticket_resolution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_resolution (
    id integer NOT NULL,
    ticket_id character varying(13),
    resolver_user_id character varying(15),
    resolution_cause text,
    description text,
    resolved_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    met_sla boolean
);


ALTER TABLE public.ticket_resolution OWNER TO postgres;

--
-- Name: ticket_resolution_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket_resolution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_resolution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_request (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.type_request OWNER TO postgres;

--
-- Name: type_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id character varying(15) NOT NULL,
    alias character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    phone character varying(11),
    password_hash character varying(100),
    departament_id integer,
    role_id integer,
    is_active boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: v_request_task; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.v_request_task AS
 SELECT id,
    ticket_id,
    priority,
    status,
    cretaed_by,
    assigned_departament,
    assigned_user,
    topic,
    description,
    created_at,
    expired_in,
    closed_in,
    ((expired_in < CURRENT_TIMESTAMP) AND (closed_in IS NULL)) AS expired
   FROM public.request_task;


ALTER VIEW public.v_request_task OWNER TO postgres;

--
-- Name: v_request_ticket; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.v_request_ticket AS
 SELECT id,
    reported_by_customer_id,
    affected_customer_id,
    ticket_bcv,
    enviroment,
    priority,
    type_request,
    sla_id,
    components_id,
    subcomponents_id,
    contact_id,
    topic,
    description,
    cretaed_by,
    created_at,
    expired_in,
    (expired_in < CURRENT_TIMESTAMP) AS expired
   FROM public.ticket_request;


ALTER VIEW public.v_request_ticket OWNER TO postgres;

--
-- Name: v_tickets_for_producto; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.v_tickets_for_producto AS
 SELECT p.id,
    p.name,
    count(t.id) AS total_tickets
   FROM ((public.product p
     JOIN public.components c ON ((p.id = c.product_id)))
     JOIN public.ticket_request t ON ((c.id = t.components_id)))
  GROUP BY p.id, p.name;


ALTER VIEW public.v_tickets_for_producto OWNER TO postgres;

--
-- Name: working_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.working_group (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.working_group OWNER TO postgres;

--
-- Name: working_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.working_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.working_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: audit_status; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_status (id, cpr_id, start_at, environment, services, description, activities, end_at, last_operation, created_at) FROM stdin;
2	9db9d164-af35-4290-a9d5-7ebbe4e04a63	2026-05-05 12:14:08	Certificacion	["Debito (002)", "Debito (003)"]	Registro en de cuenta en el Sandbox	Registro de usuario en Certificacion	2026-05-06 12:14:08	2026-05-06 12:14:08	2026-05-22 19:52:18.925474
1	9db9d164-af35-4290-a9d5-7ebbe4e04a63	2026-07-07 12:14:08	Hola mundo	["Debito (777)", "Debito (777`)"]	Registro tester update	test del update	2026-07-07 12:14:08	2026-07-07 12:14:08	2026-05-06 23:58:09.334185
\.


--
-- Data for Name: channel_reception; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.channel_reception (id, name, created_at) FROM stdin;
1	Web	2026-05-04 18:35:24.909504
\.


--
-- Data for Name: collectives; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.collectives (id, group_id, user_id, created_at) FROM stdin;
\.


--
-- Data for Name: components; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.components (id, name, product_id, description, is_active, created_at) FROM stdin;
1	MongoDB	1	Base de datos MongoDB producto sypago	t	2026-04-22 14:43:12.711699
\.


--
-- Data for Name: contact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contact (id, customer_id, name, surname, email, phone, created_at) FROM stdin;
\.


--
-- Data for Name: customer_product_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer_product_roles (id, customer_id, product_id, role_id, parent_id, created_at) FROM stdin;
4ca0672c-af23-4308-9932-8fb31287f120	2	1	1	\N	2026-05-01 15:28:54.167231
f8c7cc12-c228-4ae8-b8b3-a9418f8f7c7f	4	1	1	\N	2026-05-05 00:35:26.141121
9db9d164-af35-4290-a9d5-7ebbe4e04a63	7	1	2	4ca0672c-af23-4308-9932-8fb31287f120	2026-05-01 15:29:34.210311
3657b6a5-e25c-4986-9b40-e78d15013c06	1	1	2	4ca0672c-af23-4308-9932-8fb31287f120	2026-05-05 00:36:15.762524
d24e2b8c-e11e-4bb6-9397-9c7939426998	9	1	1	\N	2026-05-05 13:02:00.873919
e7a95b40-bb34-41ab-b006-b9da32f0750e	10	1	2	d24e2b8c-e11e-4bb6-9397-9c7939426998	2026-05-05 13:04:30.932279
b84ea47d-05b2-4371-a6a2-f752d1899483	11	1	2	d24e2b8c-e11e-4bb6-9397-9c7939426998	2026-05-05 18:58:19.025771
\.


--
-- Data for Name: customer_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer_role (id, name, created_at) FROM stdin;
1	Cliente Directo	2026-04-27 15:15:55.14066
2	Cliente Comercio	2026-05-01 14:51:35.245592
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, rif, name, channel, ws_group, uid_sypago, created_at) FROM stdin;
1	J502141588	Sentient	web	Bancaribe Sentient	\N	2026-05-01 16:00:17.22447
2	J000029490	Bancaribe	\N	\N	\N	2026-05-01 16:00:17.22447
4	J316287599	Bancamiga	\N	\N	\N	2026-05-04 23:14:31.758669
7	J301083350	Netuno	web	Netuno	\N	2026-05-04 23:40:05.906613
8	J002970553	Banco Plaza	\N	\N	\N	2026-05-04 23:41:54.269297
9	J123456987	Bancrecer	\N	\N	\N	2026-05-05 13:01:18.995046
10	J334577558	Comercio Bancrecer	web	Comercio bancrecer	\N	2026-05-05 13:02:40.527891
11	Q123456789	Alcaldia	web	Comercio bancrecer	\N	2026-05-05 18:56:00.249745
12	J00297011	Banco Tester	\N	\N	\N	2026-05-22 19:57:57.022363
\.


--
-- Data for Name: departament; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departament (id, name, is_active, created_at) FROM stdin;
3	QA	t	2026-05-22 19:31:48.654399
\.


--
-- Data for Name: environment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.environment (id, name, created_at) FROM stdin;
\.


--
-- Data for Name: item_activities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item_activities (id, product_id, name, created_at) FROM stdin;
1	1	Registro de usuario en Certificacion	2026-05-04 17:26:49.492439
2	1	Afiliacion de cuenta en Certificacion	2026-05-04 17:27:09.561903
3	1	TEST DE LABELS ITEMS	2026-05-19 13:10:01.295585
4	1	TEST DE LABELS ITEMS	2026-05-19 13:10:07.094647
10	1	TEST DE LABELS ITEMS	2026-05-22 19:51:09.387246
\.


--
-- Data for Name: notes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notes (id, ticket_id, task_id, topic, description, created_by, created_at) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, recipient_id, sender_id, ticket_id, task_id, type, title, message, read_at, created_at) FROM stdin;
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permissions (id, name, module, description, created_at) FROM stdin;
\.


--
-- Data for Name: priority; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.priority (id, name, created_at) FROM stdin;
\.


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (id, name, description, is_active, created_at) FROM stdin;
1	Sypago	Producto Sypago	t	2026-04-22 01:28:09.876251
\.


--
-- Data for Name: request_task; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.request_task (id, ticket_id, priority, status, cretaed_by, assigned_departament, assigned_user, topic, description, created_at, expired_in, closed_in) FROM stdin;
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_permissions (role_id, permissions_id, created_at) FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name, created_at) FROM stdin;
5	administrator	2026-04-21 19:28:34.157252
6	read	2026-04-21 19:28:45.510624
7	QA	2026-04-29 17:55:52.052368
26	TESTER	2026-05-22 19:24:24.662965
27	prospect	2026-05-26 20:45:37.299979
\.


--
-- Data for Name: sla; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sla (id, name, unit_time_id, amount, created_at) FROM stdin;
\.


--
-- Data for Name: status; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.status (id, name, created_at) FROM stdin;
\.


--
-- Data for Name: subcomponents; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subcomponents (id, name, components_id, description, is_active, created_at) FROM stdin;
\.


--
-- Data for Name: subproduct; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subproduct (id, name, product_id, created_at) FROM stdin;
2	Debito (003)	1	2026-05-04 18:32:59.030756
3	Credito (220)	1	2026-05-04 18:32:59.030756
1	Debito (002)	1	2026-05-04 18:32:59.030756
\.


--
-- Data for Name: task_break; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task_break (id, task_id, status_paused, start_at, end_at) FROM stdin;
\.


--
-- Data for Name: ticket_break; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket_break (id, ticket_id, status_paused, start_at, end_at) FROM stdin;
\.


--
-- Data for Name: ticket_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket_request (id, reported_by_customer_id, affected_customer_id, ticket_bcv, enviroment, priority, type_request, sla_id, components_id, subcomponents_id, contact_id, topic, description, cretaed_by, created_at, expired_in) FROM stdin;
\.


--
-- Data for Name: ticket_resolution; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket_resolution (id, ticket_id, resolver_user_id, resolution_cause, description, resolved_at, met_sla) FROM stdin;
\.


--
-- Data for Name: type_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.type_request (id, name, created_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, alias, name, surname, email, phone, password_hash, departament_id, role_id, is_active, created_at) FROM stdin;
V30221960	batman	Jose	Escalona	j.escaloca@sycom.com.ve	04129854529	$2a$10$mRFB/YacOgkTcTmo60iugehU8hqiaGIFLdJMghDX5767/CFRTJJKu	2	6	t	2026-05-26 18:45:45.329082
V123456789	maradona	maradona	maradona	maradona@sycom.com.ve	04129854529	$2a$10$Nk1Kt.ZyETjOmTyysecctexrvHBi4K5XPnK47NUu85RhOoHdGASUa	2	27	f	2026-05-26 21:37:50.694326
\.


--
-- Data for Name: working_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.working_group (id, name, created_at) FROM stdin;
\.


--
-- Name: audit_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_status_id_seq', 2, true);


--
-- Name: channel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.channel_id_seq', 1, true);


--
-- Name: collectives_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.collectives_id_seq', 1, false);


--
-- Name: components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.components_id_seq', 2, true);


--
-- Name: contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contact_id_seq', 1, false);


--
-- Name: customer_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_role_id_seq', 2, true);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 12, true);


--
-- Name: departament_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departament_id_seq', 3, true);


--
-- Name: environment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.environment_id_seq', 1, false);


--
-- Name: item_activities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_activities_id_seq', 10, true);


--
-- Name: notes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notes_id_seq', 1, false);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissions_id_seq', 1, false);


--
-- Name: priority_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.priority_id_seq', 1, false);


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 2, true);


--
-- Name: product_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_services_id_seq', 3, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 27, true);


--
-- Name: sla_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sla_id_seq', 1, false);


--
-- Name: status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.status_id_seq', 1, false);


--
-- Name: subcomponents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subcomponents_id_seq', 1, false);


--
-- Name: task_break_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_break_id_seq', 1, false);


--
-- Name: ticket_break_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_break_id_seq', 1, false);


--
-- Name: ticket_resolution_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_resolution_id_seq', 1, false);


--
-- Name: type_request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.type_request_id_seq', 1, false);


--
-- Name: working_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.working_group_id_seq', 1, false);


--
-- Name: audit_status audit_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_status
    ADD CONSTRAINT audit_status_pkey PRIMARY KEY (id);


--
-- Name: channel_reception channel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channel_reception
    ADD CONSTRAINT channel_pkey PRIMARY KEY (id);


--
-- Name: collectives collectives_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collectives
    ADD CONSTRAINT collectives_pkey PRIMARY KEY (id);


--
-- Name: components components_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT components_name_key UNIQUE (name);


--
-- Name: components components_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT components_pkey PRIMARY KEY (id);


--
-- Name: contact contact_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT contact_email_key UNIQUE (email);


--
-- Name: contact contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT contact_pkey PRIMARY KEY (id);


--
-- Name: customer_product_roles customer_product_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_product_roles
    ADD CONSTRAINT customer_product_roles_pkey PRIMARY KEY (id);


--
-- Name: customer_role customer_role_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_role
    ADD CONSTRAINT customer_role_name_key UNIQUE (name);


--
-- Name: customer_role customer_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_role
    ADD CONSTRAINT customer_role_pkey PRIMARY KEY (id);


--
-- Name: customers customers_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_name_key UNIQUE (name);


--
-- Name: customers customers_name_key1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_name_key1 UNIQUE (name);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: customers customers_rif_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_rif_key UNIQUE (rif);


--
-- Name: departament departament_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departament
    ADD CONSTRAINT departament_name_key UNIQUE (name);


--
-- Name: departament departament_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departament
    ADD CONSTRAINT departament_pkey PRIMARY KEY (id);


--
-- Name: environment environment_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environment
    ADD CONSTRAINT environment_name_key UNIQUE (name);


--
-- Name: environment environment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environment
    ADD CONSTRAINT environment_pkey PRIMARY KEY (id);


--
-- Name: ticket_break fk_unique_active_pause; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_break
    ADD CONSTRAINT fk_unique_active_pause UNIQUE (ticket_id, end_at);


--
-- Name: task_break fk_unique_active_pause_task; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_break
    ADD CONSTRAINT fk_unique_active_pause_task UNIQUE (task_id, end_at);


--
-- Name: item_activities item_activities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_activities
    ADD CONSTRAINT item_activities_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_name_key UNIQUE (name);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: priority priority_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.priority
    ADD CONSTRAINT priority_name_key UNIQUE (name);


--
-- Name: priority priority_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.priority
    ADD CONSTRAINT priority_pkey PRIMARY KEY (id);


--
-- Name: product product_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_name_key UNIQUE (name);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: subproduct product_services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subproduct
    ADD CONSTRAINT product_services_pkey PRIMARY KEY (id);


--
-- Name: request_task request_task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_task
    ADD CONSTRAINT request_task_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permissions_id);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sla sla_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sla
    ADD CONSTRAINT sla_name_key UNIQUE (name);


--
-- Name: sla sla_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sla
    ADD CONSTRAINT sla_pkey PRIMARY KEY (id);


--
-- Name: status status_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_name_key UNIQUE (name);


--
-- Name: status status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_pkey PRIMARY KEY (id);


--
-- Name: subcomponents subcomponents_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcomponents
    ADD CONSTRAINT subcomponents_name_key UNIQUE (name);


--
-- Name: subcomponents subcomponents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcomponents
    ADD CONSTRAINT subcomponents_pkey PRIMARY KEY (id);


--
-- Name: task_break task_break_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_break
    ADD CONSTRAINT task_break_pkey PRIMARY KEY (id);


--
-- Name: ticket_break ticket_break_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_break
    ADD CONSTRAINT ticket_break_pkey PRIMARY KEY (id);


--
-- Name: ticket_request ticket_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_request
    ADD CONSTRAINT ticket_request_pkey PRIMARY KEY (id);


--
-- Name: ticket_resolution ticket_resolution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_resolution
    ADD CONSTRAINT ticket_resolution_pkey PRIMARY KEY (id);


--
-- Name: type_request type_request_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_request
    ADD CONSTRAINT type_request_name_key UNIQUE (name);


--
-- Name: type_request type_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_request
    ADD CONSTRAINT type_request_pkey PRIMARY KEY (id);


--
-- Name: users users_alias_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_alias_key UNIQUE (alias);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: working_group working_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_group
    ADD CONSTRAINT working_group_name_key UNIQUE (name);


--
-- Name: working_group working_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_group
    ADD CONSTRAINT working_group_pkey PRIMARY KEY (id);


--
-- Name: customer_product_roles customer_product_roles_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_product_roles
    ADD CONSTRAINT customer_product_roles_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.customer_product_roles(id);


--
-- Name: ticket_request fk_affected_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_request
    ADD CONSTRAINT fk_affected_customer FOREIGN KEY (affected_customer_id) REFERENCES public.customers(rif);


--
-- Name: request_task fk_assigned_depart; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_task
    ADD CONSTRAINT fk_assigned_depart FOREIGN KEY (assigned_departament) REFERENCES public.departament(id) ON UPDATE CASCADE;


--
-- Name: request_task fk_assigned_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_task
    ADD CONSTRAINT fk_assigned_user FOREIGN KEY (assigned_user) REFERENCES public.users(id) ON UPDATE CASCADE;


--
-- Name: ticket_request fk_components; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_request
    ADD CONSTRAINT fk_components FOREIGN KEY (components_id) REFERENCES public.components(id) ON UPDATE CASCADE;


--
-- Name: audit_status fk_cpr_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_status
    ADD CONSTRAINT fk_cpr_id FOREIGN KEY (cpr_id) REFERENCES public.customer_product_roles(id) ON UPDATE CASCADE;


--
-- Name: request_task fk_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_task
    ADD CONSTRAINT fk_created_by FOREIGN KEY (cretaed_by) REFERENCES public.users(id) ON UPDATE CASCADE;


--
-- Name: contact fk_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES public.customers(rif);


--
-- Name: customer_product_roles fk_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_product_roles
    ADD CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON UPDATE CASCADE;


--
-- Name: collectives fk_group; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collectives
    ADD CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES public.working_group(id);


--
-- Name: components fk_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.components
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON UPDATE CASCADE;


--
-- Name: customer_product_roles fk_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_product_roles
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON UPDATE CASCADE;


--
-- Name: item_activities fk_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_activities
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON UPDATE CASCADE;


--
-- Name: subproduct fk_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subproduct
    ADD CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: ticket_request fk_reported_by_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_request
    ADD CONSTRAINT fk_reported_by_customer FOREIGN KEY (reported_by_customer_id) REFERENCES public.customers(rif);


--
-- Name: customer_product_roles fk_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_product_roles
    ADD CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES public.customer_role(id) ON UPDATE CASCADE;


--
-- Name: users fk_roles; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_roles FOREIGN KEY (role_id) REFERENCES public.roles(id) ON UPDATE CASCADE;


--
-- Name: ticket_request fk_sla; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_request
    ADD CONSTRAINT fk_sla FOREIGN KEY (sla_id) REFERENCES public.sla(id) ON UPDATE CASCADE;


--
-- Name: subcomponents fk_subcomponente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcomponents
    ADD CONSTRAINT fk_subcomponente FOREIGN KEY (components_id) REFERENCES public.components(id) ON UPDATE CASCADE;


--
-- Name: ticket_request fk_subcomponents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_request
    ADD CONSTRAINT fk_subcomponents FOREIGN KEY (subcomponents_id) REFERENCES public.subcomponents(id) ON UPDATE CASCADE;


--
-- Name: notes fk_task; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT fk_task FOREIGN KEY (task_id) REFERENCES public.request_task(id);


--
-- Name: notifications fk_task; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_task FOREIGN KEY (task_id) REFERENCES public.request_task(id);


--
-- Name: task_break fk_task; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_break
    ADD CONSTRAINT fk_task FOREIGN KEY (task_id) REFERENCES public.request_task(id) ON UPDATE CASCADE;


--
-- Name: notes fk_ticket; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT fk_ticket FOREIGN KEY (ticket_id) REFERENCES public.ticket_request(id);


--
-- Name: notifications fk_ticket; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_ticket FOREIGN KEY (ticket_id) REFERENCES public.ticket_request(id);


--
-- Name: request_task fk_ticket; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_task
    ADD CONSTRAINT fk_ticket FOREIGN KEY (ticket_id) REFERENCES public.ticket_request(id) ON UPDATE CASCADE;


--
-- Name: ticket_break fk_ticket; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_break
    ADD CONSTRAINT fk_ticket FOREIGN KEY (ticket_id) REFERENCES public.ticket_request(id) ON UPDATE CASCADE;


--
-- Name: ticket_resolution fk_ticket; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_resolution
    ADD CONSTRAINT fk_ticket FOREIGN KEY (ticket_id) REFERENCES public.ticket_request(id);


--
-- Name: ticket_resolution fk_user_resolution; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_resolution
    ADD CONSTRAINT fk_user_resolution FOREIGN KEY (resolver_user_id) REFERENCES public.users(id);


--
-- Name: collectives fk_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collectives
    ADD CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict YO0qSIbIRlvW0aI8jiFZ0dvDPRCP0OeMgbHLefTIPTK7yWXOabHUbGdbmdHhfym

